### ISSUE TITLE
Access Tabist from Pentadactyl?

### ISSUE THREAD

**Issue by alphapapa** [fiveNinePlusR/tabist#20]
Hi again,

Quick question, not sure if you can help, but: How can I access or call Tabist from Pentadactyl?  For example, I can call functions in the Pocket addon through the `RIL` object, like `:js RIL.addCurrent()` to add the current page to Pocket, as if I had clicked the button in the toolbar.

I've looked through the global namespace with Pentadactyl's autocompletion, and I've looked through the Tabist code, but I can't find any of its functions or objects in the JavaScript namespace.  Is there an intermediate object that I can access them through, or something like that?

The point of this, of course, is to be able to open Tabist by pressing a key instead of using the mouse.  :)

Thanks for your help.

**Comment by fiveNinePlusR** [comment]
Does the ctrl+shift+E shortcut work or is that overwritten by Pentadactl? 

I tried installing Pentadactyl to test it, but it seems the last supported version was firefox 30 and forcing it doesn't work because of signing issues.

**Comment by alphapapa** [comment]
Ctrl+Shift+E does work, so I guess I just need to find a way to call keyboard shortcuts from Pentadactyl...

There hasn't been an official release of Pentadactyl for quite a while, but the repo continues to be updated to work with current versions, and there's a repo of signed XPI builds here: https://github.com/willsALMANJ/pentadactyl-signed/releases  Or you can build it yourself by cloning the dactyl repo and running `make xpi` from the `dactyl` directory, which only takes a few seconds to zip up the files.

Of course I wouldn't ask you to go to all this trouble, but if you are interested anyway...  :)

...

Aha, there we go, that was easy!

```
:map gl <C-S-e>
```

Now all I have to do is press `gl` and Tabist comes up!  :D This is great!

Thanks for your help!  If you happen to be interested in using Pentadactyl, just let me know if I can help you with anything.  I've been using it for years, and I can't imagine using Firefox without it!  (Well, I can, because on other systems I do, but it's so much better with it.)

**Comment by fiveNinePlusR** [comment]
Ah. I had spoken to the developer that made the original pentadactyl that hasn't been updated in many years. 

I might try that one again but I tend to shy away from heavy extensions because they tend to slow down my (many tabbed) browser to a crawl.
