### ISSUE TITLE
Doesn't work on Firefox 50?

### ISSUE THREAD

**Issue by alphapapa** [fiveNinePlusR/tabist#21]
Hi,

I upgraded to Firefox 50, and now Tabist seems to do nothing.  When I click the button, nothing happens.  There's no right-click menu.  Pressing Ctrl+Shift+E does nothing.  I don't know what else to do.  :(

**Comment by fiveNinePlusR** [comment]
I just downloaded a firefox 50 and Tabist worked for me just fine. perhaps it's the request policy thing that you had troubles with in the past?

see issue here: https://github.com/fiveNinePlusR/tabist/issues/19

**Comment by alphapapa** [comment]
I'm using RequestPolicy Continued now, so I thought that was solved.  But I'll do some more investigating.  Thanks.

**Comment by fiveNinePlusR** [comment]
might be something else, but that's a good place to start. I'd also check the browser console to see if there are any errors.

**Comment by fiveNinePlusR** [comment]
were you able to get this working? you might have luck uninstalling and reinstalling it as well.

**Comment by alphapapa** [comment]
Thanks for reminding me.  I tried it just now and it worked!  [insert that shrug-shoulders emote thingy here]  :)

**Comment by fiveNinePlusR** [comment]
awesome 👍
