### ISSUE TITLE
An option to close tabs from tabist please

### ISSUE THREAD

**Issue by sharmi** [fiveNinePlusR/tabist#23]
It would be nice if we can close the tabs from tabist itself. I am a tab hoarder and often I end up with 100s of tabs before I realize. Closing a tab means I have to click on the tab first and that causes the tab to load (if it is not loaded). I often become aware of the number of tabs only when the system starts to crawl, so loading the tab everytime I try to close one is too painful. It would be godsend if I can close the tab without loading it.

**Comment by fiveNinePlusR** [comment]
That's a good idea and one that I had thought about a little bit before. I am not sure of the best UI for this to work well but I will play around with a few options.

**Comment by fiveNinePlusR** [comment]
fixed with 84f92080a25303e0bb3787f8c259d3bfeb00281c
