### ISSUE TITLE
Request: sidebar or dropdown list of tabs. multi-selection and actions

### ISSUE THREAD

**Issue by rayman89** [fiveNinePlusR/tabist#24]
I think it would be more swift if you could make the tab list be a drop down menu or make it a side panel that appears when you click  on a button.

Would be also nice to be able to do stuff with the tab list such as re arranging closing them muting bookmarking coping their url muting them etc and it would be great if you could make it so that you could select more than one tab at a time to do those things to.

**Comment by fiveNinePlusR** [comment]
Those are all good ideas. I have been toying with an alternate UI for tabist along with other features.

**Comment by fiveNinePlusR** [comment]
fixed in master. 

Cmd/Ctrl+shift+S is the default setting to toggle the sidebar.

**Comment by rayman89** [comment]
Control shift + s on firefox developer opens the debugger

**Comment by fiveNinePlusR** [comment]
I see. I tried that out and on a mac it doesn't do anything as it's cmd-opt-s to do that.

ideally you will be able to change this via an interface but that's not implemented from mozilla yet. do you have a shortcut that would be better on windows/linux?

**Comment by rayman89** [comment]
control + shift +z seems to not be used also control + shift +L too but that is used by other addons

**Comment by fiveNinePlusR** [comment]
does alt-shift-s work for you as that's the same keys as it is on macOS and that's pretty convenient to me. I can do ctrl-shift-z if that works better.

**Comment by rayman89** [comment]
Alt + S displays the menu option to "show all history"

**Comment by fiveNinePlusR** [comment]
I suppose i will go with ctrl-shift-z then for windows/linux
