### ISSUE TITLE
Show all audible tabs at the top of the page.

### ISSUE THREAD

**Issue by fiveNinePlusR** [fiveNinePlusR/tabist#3]

**Comment by djhworld** [comment]
Additionally would be cool if the audible tabs put the speaker emoji next to them (&#128266;) 

unicode character: &#128266;

**Comment by fiveNinePlusR** [comment]
Added the unicode character in V0.1.2. Still need to move the audible tabs to the top.

**Comment by fiveNinePlusR** [comment]
Added the audible tabs at the top of the page with V0.1.3
