### ISSUE TITLE
Chrome: refresh causes page to scroll to the top on a long list of tabs

### ISSUE THREAD

**Issue by djhworld** [fiveNinePlusR/tabist#5]
If I have a long list of tabs and I scroll down the page to find the one I want, sometimes I'm too slow and the page refreshes, which causes the browser to scroll to the top 

Steps to reproduce
1. Open a large number of tabs
2. Open tabist
3. Scroll down 

Not sure what you could do to fix it, maybe make the list turn into 2 columns on smaller displays, to mitigate scrolling? Or make the refresh interval configurable

**Comment by fiveNinePlusR** [comment]
I'll make it smarter to page changes. Right now it's a simple page refresh every few seconds. I'll have it properly update when a tab is changed/window closed.

**Comment by fiveNinePlusR** [comment]
Fixed in V0.1.2
