### ISSUE TITLE
[Feature Request] Add favicons of tabs to tabist page

### ISSUE THREAD

**Issue by djhworld** [fiveNinePlusR/tabist#6]
Next to each bullet point it would be good if the favicon appeared too (not sure if possible)

As a tab hoarder I've become accustomed to favicons as my reference point!

**Comment by fiveNinePlusR** [comment]
Great idea. I'll put this on the list

**Comment by djhworld** [comment]
Looks like it's possible in chrome at least https://developer.chrome.com/extensions/tabs#property-Tab-favIconUrl

**Comment by fiveNinePlusR** [comment]
Added in 0.1.6
