### ISSUE TITLE
[Feature Request] Option to group by domain 

### ISSUE THREAD

**Issue by djhworld** [fiveNinePlusR/tabist#7]
Would be good if you could hit a switch to group my tabs by their base domain

For example if you had 3 tabs open for youtube.com, 3 tabs open for reddit and other sites, the Tabist tab would group ones with the same domain together

Combined with #6 this would be great for me, for consolidation at least and quick visual reference!

crude drawing: 

![image](https://cloud.githubusercontent.com/assets/529730/17344315/8bc578ba-58f9-11e6-8353-f21b622bc5c9.png)

**Comment by fiveNinePlusR** [comment]
@djhworld hope the new version helps you out.
